vscode:
  extensions:
    - astro-build.astro-vscode
tasks:
  - before: |
      # Update node version and run first sample
    init: |
      nvm install 18.12.1
    command: |
      chmod a+x .gitpod/gitpod-setup.sh
      .gitpod/gitpod-setup.sh
ports:
  - port: 3000
    onOpen: open-preview
